import { db, productsTable, quotationsTable } from "@workspace/db";

const categories = [
  { slug: "flasks", name: "Flasks" },
  { slug: "mug-glass", name: "Mug/Glass" },
  { slug: "laptop-bags", name: "Laptop Bags" },
  { slug: "backpacks", name: "Backpacks" },
  { slug: "travel-bags", name: "Travel Bags" },
  { slug: "clocks", name: "Table Clocks and Wall Clocks" },
  { slug: "diaries", name: "Diaries" },
  { slug: "calendars", name: "Calendars" },
  { slug: "notebooks", name: "Notebooks" },
  { slug: "leather", name: "Leather Wallets and Leather Bags" },
  { slug: "pens", name: "Pens and Pen Sets" },
  { slug: "keychains", name: "Key Chains" },
  { slug: "card-holders", name: "Visiting Card Holders" },
  { slug: "gift-sets", name: "Gift Sets" },
  { slug: "novelties", name: "Novelties" },
];

const products = [
  // Flasks
  {
    name: "Executive Stainless Steel Flask",
    description: "Premium double-wall vacuum insulated flask, keeps beverages hot for 12 hours. Laser-engraving available.",
    category: "Flasks",
    categorySlug: "flasks",
    basePrice: 850,
    discountPrice: 720,
    minNegotiationPrice: 650,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Available in silver, black, and gold. Custom logo engraving available for orders above 50 units.",
    bulkPricingNotes: "50+ units: ₹650 | 100+ units: ₹600 | 200+ units: ₹550",
  },
  {
    name: "Slim Travel Flask",
    description: "Compact 350ml flask, ideal for travel and corporate gifting. Leak-proof lid with carry strap.",
    category: "Flasks",
    categorySlug: "flasks",
    basePrice: 480,
    discountPrice: 400,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Fixed pricing. Available in 5 colors.",
    bulkPricingNotes: null,
  },
  {
    name: "Copper Flask Premium",
    description: "Handcrafted copper finish flask with embossed floral design. 500ml capacity, excellent for gifting.",
    category: "Flasks",
    categorySlug: "flasks",
    basePrice: 1200,
    discountPrice: null,
    minNegotiationPrice: 1000,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "low_stock" as const,
    notes: "Limited stock — artisan crafted.",
    bulkPricingNotes: "Bulk orders over 20 units: contact for special pricing.",
  },
  // Mug/Glass
  {
    name: "Executive Ceramic Mug",
    description: "11oz premium ceramic mug with custom print area. Dishwasher safe, ideal for office gifting.",
    category: "Mug/Glass",
    categorySlug: "mug-glass",
    basePrice: 280,
    discountPrice: 240,
    minNegotiationPrice: 200,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Full-color wrap printing or single-color logo.",
    bulkPricingNotes: "100+ units: ₹200 | 500+ units: ₹175",
  },
  {
    name: "Magic Color-Change Mug",
    description: "Heat-sensitive mug that reveals a message or design when filled with hot liquid. Great novelty gift.",
    category: "Mug/Glass",
    categorySlug: "mug-glass",
    basePrice: 350,
    discountPrice: 300,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Custom design printed on heat-reactive coating.",
    bulkPricingNotes: "Minimum order: 50 units.",
  },
  {
    name: "Borosilicate Glass Mug Set",
    description: "Set of 2 borosilicate glass mugs with handles. Elegant, transparent, and heat-resistant.",
    category: "Mug/Glass",
    categorySlug: "mug-glass",
    basePrice: 550,
    discountPrice: null,
    minNegotiationPrice: 480,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Comes in gift box. Custom engraving on the handle ring.",
    bulkPricingNotes: null,
  },
  // Laptop Bags
  {
    name: "Executive Leather Laptop Bag",
    description: "Genuine leather 15.6\" laptop bag with padded compartment, organizer pockets, and carry handles.",
    category: "Laptop Bags",
    categorySlug: "laptop-bags",
    basePrice: 3500,
    discountPrice: 2999,
    minNegotiationPrice: 2700,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Available in black and tan. Embossing available.",
    bulkPricingNotes: "10+ units: ₹2,700 | 25+ units: ₹2,500",
  },
  {
    name: "Canvas Laptop Messenger Bag",
    description: "Heavy-duty canvas messenger bag with laptop sleeve for 14\". Multiple pockets and adjustable strap.",
    category: "Laptop Bags",
    categorySlug: "laptop-bags",
    basePrice: 1800,
    discountPrice: 1500,
    minNegotiationPrice: 1300,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Custom logo screen printing available.",
    bulkPricingNotes: "20+ units: ₹1,300",
  },
  // Backpacks
  {
    name: "Corporate Backpack Pro",
    description: "Spacious 30L polyester backpack with laptop sleeve, USB charging port, and reflective strips.",
    category: "Backpacks",
    categorySlug: "backpacks",
    basePrice: 2200,
    discountPrice: 1899,
    minNegotiationPrice: 1700,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Available in charcoal, navy, and olive.",
    bulkPricingNotes: "15+ units: ₹1,700 | 30+ units: ₹1,550",
  },
  {
    name: "Mini Campus Backpack",
    description: "Compact 18L daypack with front organizer pocket. Great for team outings and events.",
    category: "Backpacks",
    categorySlug: "backpacks",
    basePrice: 950,
    discountPrice: 799,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Available in 8 colors. Custom embroidery patch available.",
    bulkPricingNotes: "50+ units: ₹750",
  },
  // Travel Bags
  {
    name: "Weekender Duffle Bag",
    description: "Large 50L duffle with wet-dry separation, shoe compartment, and padded shoulder strap.",
    category: "Travel Bags",
    categorySlug: "travel-bags",
    basePrice: 2800,
    discountPrice: 2400,
    minNegotiationPrice: 2100,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Custom embroidery on front panel.",
    bulkPricingNotes: "10+ units: ₹2,100",
  },
  {
    name: "Rolling Trolley Bag 20\"",
    description: "Cabin-size hard-shell trolley with spinner wheels and TSA lock. Perfect for business travel gifting.",
    category: "Travel Bags",
    categorySlug: "travel-bags",
    basePrice: 5500,
    discountPrice: null,
    minNegotiationPrice: 5000,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "low_stock" as const,
    notes: "Available in 4 colors. Personalized name tag included.",
    bulkPricingNotes: "5+ units: ₹5,000",
  },
  // Clocks
  {
    name: "Mahogany Desk Clock",
    description: "Elegant wooden desk clock with quartz movement. Gold or silver hands, customizable dial face.",
    category: "Table Clocks and Wall Clocks",
    categorySlug: "clocks",
    basePrice: 1200,
    discountPrice: 999,
    minNegotiationPrice: 900,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Custom text or logo on the dial. Batteries included.",
    bulkPricingNotes: "20+ units: ₹900",
  },
  {
    name: "Metal Wall Clock",
    description: "Modern brushed aluminum wall clock with silent sweep movement. 30cm diameter, ideal for corporate offices.",
    category: "Table Clocks and Wall Clocks",
    categorySlug: "clocks",
    basePrice: 1800,
    discountPrice: 1500,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Company logo on the center cap. Comes in gift packaging.",
    bulkPricingNotes: null,
  },
  // Diaries
  {
    name: "Executive Leather Diary A5",
    description: "Premium PU leather bound diary, 200 pages, ribbon bookmark, elastic closure. Lay-flat binding.",
    category: "Diaries",
    categorySlug: "diaries",
    basePrice: 650,
    discountPrice: 550,
    minNegotiationPrice: 480,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Custom logo debossing on cover. Gilt-edge pages available.",
    bulkPricingNotes: "50+ units: ₹480 | 100+ units: ₹440",
  },
  {
    name: "Hardbound Diary with Pen",
    description: "Hardbound dairy with matching pen set. 160 ruled pages with monthly planner at start.",
    category: "Diaries",
    categorySlug: "diaries",
    basePrice: 450,
    discountPrice: 380,
    minNegotiationPrice: 340,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Complete gift set in branded sleeve.",
    bulkPricingNotes: "100+ units: ₹340",
  },
  // Calendars
  {
    name: "Desk Easel Calendar",
    description: "12-month desk easel calendar with high-quality photo prints. Custom branding on every page.",
    category: "Calendars",
    categorySlug: "calendars",
    basePrice: 300,
    discountPrice: 250,
    minNegotiationPrice: 200,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Minimum order 100 units. Artwork to be provided by client.",
    bulkPricingNotes: "100+ units: ₹200 | 500+ units: ₹170",
  },
  {
    name: "Wall Calendar A3",
    description: "Large-format A3 wall calendar, spiral-bound, 13 pages (cover + 12 months). Custom images per page.",
    category: "Calendars",
    categorySlug: "calendars",
    basePrice: 180,
    discountPrice: null,
    minNegotiationPrice: 150,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Minimum order 200 units.",
    bulkPricingNotes: "200+ units: ₹150 | 1000+ units: ₹120",
  },
  // Notebooks
  {
    name: "Moleskine-Style Hardcover Notebook",
    description: "Premium hardcover notebook, 192 pages, dotted or ruled. Elastic band closure, ribbon bookmark.",
    category: "Notebooks",
    categorySlug: "notebooks",
    basePrice: 420,
    discountPrice: 350,
    minNegotiationPrice: 300,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Available in A5 and B5. Cover logo embossing available.",
    bulkPricingNotes: "50+ units: ₹300 | 200+ units: ₹270",
  },
  {
    name: "Recycled Paper Notebook",
    description: "Eco-friendly recycled kraft paper notebook. 80 pages, unlined. Perfect for sustainable gifting.",
    category: "Notebooks",
    categorySlug: "notebooks",
    basePrice: 220,
    discountPrice: 180,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Eco-conscious gift choice. Seed paper bookmark included.",
    bulkPricingNotes: "100+ units: ₹165",
  },
  // Leather
  {
    name: "Slim Leather Wallet",
    description: "Genuine leather slim wallet with 6 card slots, bill compartment, and RFID blocking.",
    category: "Leather Wallets and Leather Bags",
    categorySlug: "leather",
    basePrice: 850,
    discountPrice: 720,
    minNegotiationPrice: 650,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Available in black and tan. Custom initials hot stamping available.",
    bulkPricingNotes: "25+ units: ₹650",
  },
  {
    name: "Executive Leather Briefcase",
    description: "Full-grain leather briefcase with combination lock. Fits 15\" laptop, multiple interior pockets.",
    category: "Leather Wallets and Leather Bags",
    categorySlug: "leather",
    basePrice: 6500,
    discountPrice: null,
    minNegotiationPrice: 6000,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "low_stock" as const,
    notes: "Handcrafted, limited availability. Personalization available.",
    bulkPricingNotes: "5+ units: ₹6,000",
  },
  // Pens
  {
    name: "Parker-Style Ball Pen",
    description: "Premium metal ballpen with smooth ink flow. Blue/black refill. Elegant chrome clip and trim.",
    category: "Pens and Pen Sets",
    categorySlug: "pens",
    basePrice: 350,
    discountPrice: 280,
    minNegotiationPrice: 240,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Laser engraving on barrel. Available in gift box.",
    bulkPricingNotes: "50+ units: ₹240 | 200+ units: ₹210",
  },
  {
    name: "3-Pen Gift Set",
    description: "Gift set of 3 matching metal pens — ball pen, roller pen, and gel pen — in a magnetic gift box.",
    category: "Pens and Pen Sets",
    categorySlug: "pens",
    basePrice: 950,
    discountPrice: 799,
    minNegotiationPrice: 700,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Luxury gift presentation. Logo engraving on each pen.",
    bulkPricingNotes: "20+ units: ₹700",
  },
  // Keychains
  {
    name: "Metal Keychain with Charm",
    description: "Heavy-duty zinc alloy keychain with polished finish. Laser engraving or enamel fill customization.",
    category: "Key Chains",
    categorySlug: "keychains",
    basePrice: 120,
    discountPrice: 95,
    minNegotiationPrice: 75,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "MOQ 100 units. Multishape options available.",
    bulkPricingNotes: "100+ units: ₹75 | 500+ units: ₹60",
  },
  {
    name: "Leather Keychain",
    description: "Genuine leather keychain with brass hardware. Initials or logo embossed.",
    category: "Key Chains",
    categorySlug: "keychains",
    basePrice: 180,
    discountPrice: 150,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Premium feel at an accessible price point.",
    bulkPricingNotes: "200+ units: ₹130",
  },
  // Card Holders
  {
    name: "Metal Visiting Card Holder",
    description: "Stainless steel business card holder with mirror polish. Holds up to 30 cards. Logo laser-etched.",
    category: "Visiting Card Holders",
    categorySlug: "card-holders",
    basePrice: 450,
    discountPrice: 380,
    minNegotiationPrice: 320,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Popular executive gift. Available in gold and silver.",
    bulkPricingNotes: "50+ units: ₹320 | 100+ units: ₹290",
  },
  {
    name: "Leather Card Case",
    description: "Slim genuine leather visiting card case. 20-card capacity, magnetic snap closure.",
    category: "Visiting Card Holders",
    categorySlug: "card-holders",
    basePrice: 550,
    discountPrice: null,
    minNegotiationPrice: 480,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Monogramming available.",
    bulkPricingNotes: null,
  },
  // Gift Sets
  {
    name: "Corporate Starter Gift Set",
    description: "A curated gift set including a ceramic mug, ballpen, and A5 notebook in a branded gift box.",
    category: "Gift Sets",
    categorySlug: "gift-sets",
    basePrice: 1200,
    discountPrice: 999,
    minNegotiationPrice: 880,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Box can be custom printed. Great for employee onboarding and events.",
    bulkPricingNotes: "25+ sets: ₹880 | 50+ sets: ₹820",
  },
  {
    name: "Premium Executive Gift Set",
    description: "High-end set with leather diary, roller pen, business card holder, and stainless flask in a wooden box.",
    category: "Gift Sets",
    categorySlug: "gift-sets",
    basePrice: 3800,
    discountPrice: 3299,
    minNegotiationPrice: 3000,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Ideal for directors, CXO-level gifting, and festive seasons.",
    bulkPricingNotes: "10+ sets: ₹3,000 | 25+ sets: ₹2,800",
  },
  {
    name: "Wellness Gift Set",
    description: "Health-focused set with insulated bottle, stress ball, aromatherapy candle, and branded tote bag.",
    category: "Gift Sets",
    categorySlug: "gift-sets",
    basePrice: 1800,
    discountPrice: 1500,
    minNegotiationPrice: null,
    isNegotiable: false,
    isVisible: true,
    stockStatus: "low_stock" as const,
    notes: "Trending for employee wellness programs.",
    bulkPricingNotes: "20+ sets: ₹1,400",
  },
  // Novelties
  {
    name: "Customizable Jigsaw Puzzle",
    description: "500-piece jigsaw puzzle featuring a custom image or design. Comes in a branded box.",
    category: "Novelties",
    categorySlug: "novelties",
    basePrice: 450,
    discountPrice: 380,
    minNegotiationPrice: 320,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Great for team events and milestone celebrations.",
    bulkPricingNotes: "30+ units: ₹320",
  },
  {
    name: "Wooden Desk Organizer",
    description: "Bamboo desk organizer with compartments for pens, phone, and stationery. Laser-engraved branding.",
    category: "Novelties",
    categorySlug: "novelties",
    basePrice: 680,
    discountPrice: 580,
    minNegotiationPrice: 520,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "in_stock" as const,
    notes: "Eco-friendly bamboo. Available in 3 finishes.",
    bulkPricingNotes: "20+ units: ₹520",
  },
  {
    name: "Customized Bobblehead",
    description: "Hand-crafted caricature bobblehead of a person or mascot. Fully customized from a photo.",
    category: "Novelties",
    categorySlug: "novelties",
    basePrice: 2800,
    discountPrice: null,
    minNegotiationPrice: 2500,
    isNegotiable: true,
    isVisible: true,
    stockStatus: "low_stock" as const,
    notes: "Lead time 3-4 weeks. Ideal for retirement and appreciation gifts.",
    bulkPricingNotes: "5+ units: ₹2,500",
  },
];

async function seed() {
  console.log("Seeding products...");

  await db.delete(quotationsTable);
  await db.delete(productsTable);

  await db.insert(productsTable).values(products);

  console.log(`Seeded ${products.length} products across ${categories.length} categories.`);
}

seed()
  .then(() => {
    console.log("Done.");
    process.exit(0);
  })
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
